# Python
import torch

# Third party
from peft import PeftModel
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

# Local
from utils import BASE_MODEL_ID, MICROSERVICES_MODEL_DIR


SAMPLE_PROMPT = """// File: ./api/controllers/product.ts
import { Request, Response } from 'express';

interface ProductBody {
  name: string;
  price: number;
  category: string;
}

export const registerProduct = async (req: Request, res: Response) => {
  try {
    const payload = req.body as ProductBody;

    if (!payload.name || !payload.price || !payload.category) {
      return res.status(400).json({ message:"""


def load_model_and_tokenizer():
    """Load the base model and the trained adapter for generation.

    Returns:
        tuple: Model and tokenizer instances ready for inference.
    """
    quantization_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_use_double_quant=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.bfloat16,
    )

    base_model = AutoModelForCausalLM.from_pretrained(
        BASE_MODEL_ID,
        quantization_config=quantization_config,
        device_map="auto",
    )
    model = PeftModel.from_pretrained(base_model, MICROSERVICES_MODEL_DIR)
    tokenizer = AutoTokenizer.from_pretrained(MICROSERVICES_MODEL_DIR)
    return model, tokenizer


def generate_code_completion(model, tokenizer, prompt: str, max_new_tokens: int = 300) -> str:
    """Generate a code completion from the given prompt.

    Args:
        model: Loaded model instance.
        tokenizer: Tokenizer associated with the model.
        prompt (str): Input code snippet.
        max_new_tokens (int): Maximum number of generated tokens.

    Returns:
        str: Decoded output text generated by the model.
    """
    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
    outputs = model.generate(
        input_ids=inputs["input_ids"],
        attention_mask=inputs.get("attention_mask"),
        max_new_tokens=max_new_tokens,
        min_new_tokens=120,
        repetition_penalty=1.18,
        temperature=0.05,
        top_p=0.85,
        do_sample=True,
        pad_token_id=tokenizer.eos_token_id,
    )
    return tokenizer.decode(outputs[0], skip_special_tokens=True)


def main() -> None:
    """Run an inference example using the trained adapter.

    Returns:
        None: This function does not return a value.
    """
    print("Loading the model and tokenizer...")
    model, tokenizer = load_model_and_tokenizer()

    print("Generating code completion...")
    result = generate_code_completion(model, tokenizer, SAMPLE_PROMPT)

    print("=================== RESULT ===================")
    print(result)
    print("==============================================")


if __name__ == "__main__":
    main()